spring.datasource.url=jdbc:postgresql://localhost:5432/ordersdb
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
spring.application.name=demo
